name: Docker Build and Deploy

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: deenk8s-webapp
  DOCKER_HUB_USERNAME: fullbloodprince

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      run: docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        pwd
        docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::8} ./APP/
        docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::8}

    - name: Update Kubernetes manifest
      run: |
        IMAGE_TAG=${GITHUB_SHA::8}
        sed -i "s|image: .*|image: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG|" kube_manifest/deployment.yaml 

    - name: Commit and push manifest changes 
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add kube_manifest/deployment.yaml
        git commit -m "Update image tag in deployment.yaml"
        git push
